import re
import anndata as ad
import phenograph
import argparse
from pathlib import Path
from utils import subset_downstream_expr_by_channel

parser = argparse.ArgumentParser(prog='Phenograph clustering',
                                 description='Perform phenograph clustering on an h5ad intensity object.')

# I/O Arguments
parser.add_argument("-i", "--input", dest="input", action="store", default="", help="Input h5ad file.")
parser.add_argument("-o", "--output", dest="output", action="store", default="", help="Output h5ad file.")
parser.add_argument("-k", "--nearest-neighbors", dest="k", action="store", type=int, default=30,
                    help="K value nearest neighbors to use in phenograph. Default is 30")
parser.add_argument("-m", "--min-cluster-size", dest="min_clust", action="store", type=int, default=10,
                    help="Minimum cluster size to use in phenograph. Default is 10")
parser.add_argument("-n", "--normalize", dest="normalize", action="store_true",
                    help="Column normalize the expression intensities prior to clustering.")
parser.add_argument("-ci", "--channels-ignore", dest="channels_ignore", action="store", default="None",
                    type=str, help="Space separated string of channels to ignore.", required=False, nargs="+")
parser.add_argument("-p", "--panel", dest="panel", action="store", default="panel.csv",
                    help="Panel file generated by the pipeline.")

args = parser.parse_args()

export = ad.read_h5ad(args.input)

export.obs['mask_id'] = [int(re.search(r'\d+', elem).group()) for elem in
                                           export.obs.index]

# column normalize?
expr = ((export.X - export.X.min()) / (export.X.max() - export.X.min())) if args.normalize else export.X

expr = subset_downstream_expr_by_channel(args.channels_ignore, args.panel,
                                         export, expr)

communities, graph, Q = phenograph.cluster(expr, k=args.k, min_cluster_size=args.min_clust)

export.obs['phenograph'] = communities

export.write_h5ad(Path(args.output))