from typing import Union
import pandas as pd
import numpy as np
import anndata as ad

def subset_downstream_expr_by_channel(channels_ignore: Union[list, str],
                                      panel_file: str,
                                      export: ad.AnnData,
                                      expr: np.array):
    """
    Subset the expression array used for clustering and UMAP by ignoring designated channels.
    :param channels_ignore: List or space separated string of channels to ignore
    :param panel_file: path to a `panel.csv` file generated by steinbock
    :param export: `Anndata` object containing the exported object quantification values
    :param expr: The `export.X` array of object intensities
    :return: Subset expression array with listed channels removed
    """
    
    if channels_ignore and channels_ignore not in ["None", None, ['None'], [None]]:

        chan_list_ignore = channels_ignore if (isinstance(channels_ignore, list)) else \
        [str(i) for i in channels_ignore.split()]

        if chan_list_ignore:

            panel = pd.read_csv(panel_file)

            chan_to_label = dict(zip(panel['channel'], panel['name']))

            to_ignore = [int(list(export.var_names).index(chan_to_label[i])) for i in chan_list_ignore if
                 i in list(chan_to_label.keys())]

            expr = np.delete(expr, to_ignore, axis=1)

    return expr